import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

part 'accounting.freezed.dart';
part 'accounting.g.dart';
// Generated by https://quicktype.io

@freezed
abstract class Accounting with _$Accounting {
  factory Accounting({List<AccountingElement> accounting, List<AccountingElement> sales}) = _Accounting;
  factory Accounting.fromJson(Map<String, dynamic> json) =>_$AccountingFromJson(json);
}

@freezed
abstract class AccountingElement with _$AccountingElement {
  factory AccountingElement({String firstName, String lastName, int age}) = _AccountingElement;
  factory AccountingElement.fromJson(Map<String, dynamic> json) => _$AccountingElementFromJson(json);
}
